/* User Action Types */
export const HANDLE_USER = 'HANDLE_USER'

/* Common Action Types */
export const HANDLE_UTIL_ALERT = 'HANDLE_UTIL_ALERT'
export const HANLE_SELECTED_THEME = 'HANLE_SELECTED_THEME'

/* Repositories Action Types */
export const HANDLE_LIST_REPOSITORIES = 'HANDLE_LIST_REPOSITORIES'
export const HANDLE_FAVORITES_REPOSITORIES = 'HANDLE_FAVORITES_REPOSITORIES'
